name: Run Linter

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - NonProd

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_ALL_CODEBASE: false
