name: Validate Python

# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Runs the Super-Linter action
      - name: Run Super-Linter
        #uses: github/super-linter@v3
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_ALL_CODEBASE: false

      - name: Run pytest
        run: |
          python -m pytest --verbose --color=yes

      # - name: Terraform Test
      #   uses: docker://hasicorp/terraform:0.12.0
      #   run: |
      #     echo "1 + 5" | terraform console

      - uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 0.12.0
      
      - name: Terraform console
        run: echo "1+5" | terraform console
