name: Run Tests

# Run this on Pull Requests into master branch
on:
  pull_request:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Install pytest dependancies
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run pytest
      - name: Run pytest
        run: |
          python -m pytest --verbose --color=yes
